/*  A random word will be selected from this array */

exports.possibleWords = [
  "api",
  "algorithm",
  "array",
  "arrow functions",
  "anonymous function",
  "binary",
  "byte",
  "client",
  "class",
  "constructor",
  "callback",
  "database",
  "declarations",
  "domain",
  "dynamic",
  "expression",
  "function",
  "hyperlink",
  "iteration",
  "json",
  "methods",
  "objects",
  "promise",
  "parameters",
  "prototype",
  "recursion",
  "statement",
  "variable"
];
